CREATE USER KAA IDENTIFIED BY 12345 
DEFAULT TABLESPACE USERS 
QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, 
      CREATE PUBLIC SYNONYM, DROP PUBLIC SYNONYM, 
      CREATE MATERIALIZED VIEW, 
      CREATE VIEW, 
      CREATE CLUSTER,
      CREATE SEQUENCE,
      CREATE TABLE 
TO KAA;
GRANT CREATE SYNONYM TO KAA;

-- 2
CREATE SEQUENCE S1
  START WITH 1000
  INCREMENT BY 10
  NOMINVALUE
  NOMAXVALUE
  NOCYCLE
  NOCACHE
  NOORDER;

SELECT S1.NEXTVAL FROM DUAL;
SELECT S1.NEXTVAL FROM DUAL;
SELECT S1.NEXTVAL FROM DUAL;
SELECT S1.CURRVAL FROM DUAL;

drop SEQUENCE S1;

-- 3
CREATE SEQUENCE S2
  START WITH 10
  INCREMENT BY 10
  MAXVALUE 100
  NOCYCLE;

DROP SEQUENCE S2;
-- 4
BEGIN
  FOR i IN 1..11 LOOP
    DBMS_OUTPUT.PUT_LINE(S2.NEXTVAL);
  END LOOP;
END;
/

-- 5
CREATE SEQUENCE S3
  START WITH 10
  INCREMENT BY -10
  MINVALUE -100
  MAXVALUE 10
  NOCYCLE
  ORDER;

DROP SEQUENCE S3;

BEGIN
  FOR i IN 1..13 LOOP 
    DBMS_OUTPUT.PUT_LINE(S3.NEXTVAL);
  END LOOP;
END;
/

-- 6 ?
CREATE SEQUENCE S4
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 10
  CYCLE
  CACHE 5
  NOORDER;

SELECT S4.NEXTVAL FROM DUAL CONNECT BY LEVEL <= 15;

-- 7
SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, LAST_NUMBER 
FROM USER_SEQUENCES;

-- 8
CREATE TABLE T1 (
  N1 NUMBER(20),
  N2 NUMBER(20),
  N3 NUMBER(20),
  N4 NUMBER(20)
)
STORAGE (BUFFER_POOL KEEP)
CACHE;

INSERT INTO T1 (N1, N2, N3, N4) VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
COMMIT;

select * from T1;

-- 9
CREATE CLUSTER ABC (
  X NUMBER(10),
  V VARCHAR2(12)
)
SIZE 200 
HASHKEYS 200;
drop CLUSTER ABC;

-- 10
CREATE TABLE A (
  XA NUMBER(10),
  VA VARCHAR2(12),
  DT DATE
)
CLUSTER ABC (XA, VA);

-- 11
CREATE TABLE B (
  XB NUMBER(10),
  VB VARCHAR2(12),
  QQ NUMBER
)
CLUSTER ABC (XB, VB);

-- 12
CREATE TABLE C (
  XC NUMBER(10),
  VC VARCHAR2(12),
  ZZ VARCHAR2(50)
)
CLUSTER ABC (XC, VC);

-- 13
SELECT TABLE_NAME, CLUSTER_NAME FROM USER_TABLES WHERE CLUSTER_NAME = 'ABC';
SELECT CLUSTER_NAME, CLUSTER_TYPE, HASHKEYS FROM USER_CLUSTERS WHERE CLUSTER_NAME = 'ABC';

-- 14
CREATE SYNONYM SYNC FOR C;
INSERT INTO SYNC (XC, VC) VALUES (1, 'test');
SELECT * FROM SYNC;

-- 15
CREATE PUBLIC SYNONYM PUB_B FOR KAA.B;
SELECT * FROM PUB_B;

-- 16
CREATE TABLE TAB_MAIN (
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(50)
);

CREATE TABLE TAB_CHILD (
  ID NUMBER PRIMARY KEY,
  MAIN_ID NUMBER REFERENCES TAB_MAIN(ID),
  DETAILS VARCHAR2(50)
);

INSERT INTO TAB_MAIN VALUES (1, '1');
INSERT INTO TAB_MAIN VALUES (2, '2');
INSERT INTO TAB_CHILD VALUES (100, 1, '1.1');
INSERT INTO TAB_CHILD VALUES (101, 1, '1.2');
COMMIT;

CREATE OR REPLACE VIEW V1 AS
SELECT m.NAME, c.DETAILS
FROM TAB_MAIN m INNER JOIN TAB_CHILD c ON m.ID = c.MAIN_ID;

SELECT * FROM V1;

-- 17
CREATE MATERIALIZED VIEW MV_TEST
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
START WITH SYSDATE NEXT SYSDATE + (2 / (24 * 60))
AS
SELECT m.NAME, COUNT(c.ID) as CHILD_COUNT
FROM TAB_MAIN m
LEFT JOIN TAB_CHILD c ON m.ID = c.MAIN_ID
GROUP BY m.NAME;

SELECT * FROM MV_TEST;

SELECT * FROM TAB_MAIN;
SELECT * FROM TAB_CHILD;
INSERT INTO TAB_MAIN VALUES (3, '3');
INSERT INTO TAB_CHILD VALUES (102, 1, '1.3');
INSERT INTO TAB_CHILD VALUES (103, 3, '3.1');
INSERT INTO TAB_CHILD VALUES (103, 3, '4.1');
COMMIT;
DELETE FROM TAB_CHILD WHERE ID=100;

EXEC DBMS_MVIEW.REFRESH('MV_TEST');